{
	"_Type": "Action.Type.ProgressBanner",
	"OnSuccess": "/AuditoriaMobile/Actions/Application/AppUpdate.action",
	"Message": "Buscando actualizaciones...",
	"CompletionTimeout": 3,
	"Animated": true
}