{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "OnWillUpdate"
	},
	"Message": "Ya está disponible una nueva versión de la aplicación. ¿Quieres actualizar a esta versión?",
	"Title": "¡Nueva versión disponible!",
	"OKCaption": "Ahora",
	"CancelCaption": "Luego"
}