{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "TipoAuditoria_DeleteConfirmation"
	},
	"Message": "¿Esta seguro de eliminar {TipoAuditoria/DESCRIPCION}?",
	"Title": "Confirmar eliminación",
	"OKCaption": "Aceptar",
	"CancelCaption": "Cancelar"
}