{
	"_Type": "Action.Type.ProgressBanner",
	"OnSuccess": "/AuditoriaMobile/Actions/Auditoria/Service/DownloadOffline.action",
	"Message": "Descarga en progreso...",
	"CompletionMessage": "Descargar exitosa",
	"CompletionTimeout": 7
}