{
	"_Type": "Action.Type.ODataService.Initialize",
	"ActionResult": {
		"_Name": "init"
	},
	"OnFailure": "/AuditoriaMobile/Actions/Auditoria/Service/InitializeOfflineFailureMessage.action",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Downloading...",
	"Service": "/AuditoriaMobile/Services/Auditoria.service",
	"DefiningRequests": [
		{
			"Name": "Auditoria",
			"Query": "Auditoria",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "Recomendacion",
			"Query": "Recomendacion"
		},
		{
			"Name": "TipoAuditoria",
			"Query": "TipoAuditoria"
		}
	]
}