{
	"_Type": "Action.Type.ProgressBanner",
	"OnFailure": "/AuditoriaMobile/Actions/Auditoria/Service/SyncFailureMessage.action",
	"OnSuccess": "/AuditoriaMobile/Actions/Auditoria/Service/UploadOffline.action",
	"Message": "Subida en progreso...",
	"CompletionMessage": "Sincronización finalizada",
	"CompletionTimeout": 7,
	"Animated": true
}