{
    "Message": "Upload in progress...",
    "CompletionMessage": "Sync completed",
    "CompletionTimeout": 7,
    "OnSuccess": "/AuditoriaMobile/Actions/Auditoria/Service/UploadOffline.action",
    "OnFailure": "/AuditoriaMobile/Actions/Auditoria/Service/SyncFailureMessage.action",
    "_Type": "Action.Type.ProgressBanner"
}