{
    "Service": "/AuditoriaMobile/Services/Auditoria.service",
    "_Type": "Action.Type.OfflineOData.Upload",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnSuccess": "/AuditoriaMobile/Actions/Auditoria/Service/DownloadStartedMessage.action",
    "OnFailure": "/AuditoriaMobile/Actions/Auditoria/Service/SyncFailureMessage.action"
}