{
	"_Type": "Action.Type.OfflineOData.Upload",
	"ActionResult": {
		"_Name": "sync"
	},
	"OnFailure": "/AuditoriaMobile/Actions/Auditoria/Service/SyncFailureMessage.action",
	"OnSuccess": "/AuditoriaMobile/Actions/Auditoria/Service/DownloadStartedMessage.action",
	"Service": "/AuditoriaMobile/Services/Auditoria.service"
}