{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "Auditoria_DeleteConfirmation"
	},
	"Message": "¿Esta seguro de eliminar la auditoría?",
	"Title": "Confirmar eliminación",
	"OKCaption": "OK",
	"CancelCaption": "Cancel"
}