{
	"_Type": "Action.Type.ODataService.DeleteEntity",
	"ActionResult": {
		"_Name": "Auditoria_DeleteEntity"
	},
	"OnFailure": "/AuditoriaMobile/Actions/DeleteAuditoriaEntityFailureMessage.action",
	"OnSuccess": "/AuditoriaMobile/Actions/CloseModalPage_Complete.action",
	"Target": {
		"Service": "/AuditoriaMobile/Services/Auditoria.service",
		"EntitySet": "Auditoria",
		"ReadLink": "{@odata.readLink}"
	}
}