{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "Confirmation"
	},
	"Message": "¿Quieres salir de la aplicación actual?",
	"Title": "Confirmar",
	"OKCaption": "Aceptar",
	"CancelCaption": "Cancelar"
}